[package]
name = "lfconf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Biblioteka klienta i storage do lfconfd - konfiguracji lfshell"

[features]
default = []
gtk4 = ["dep:gtk4", "dep:glib"] #

[dependencies]
tokio = { workspace = true, features = ["rt", "fs"] }
zbus.workspace = true
serde.workspace = true
ron.workspace = true
parking_lot.workspace = true
futures-util.workspace = true
gtk4.workspace = true
glib.workspace = true
